// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Noise environment registry reached for one registered executor.
 */
export type EnvironmentNoiseRegistry = {
/**
 * Registry base URL; `/cloud/environment/{environmentId}/connect` is appended.
 */
url: string,
/**
 * Environment id the executor registered with.
 */
environmentId: string,
/**
 * Bearer token for the registry's harness requests.
 */
authToken: string, };
